name = "Kirisute Gomen Mc Skyblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caa9181d5d804eb8029053ac69309ad2db982f62df9e4bbd3571eea621cbe113"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
