name = "Kirisute Gomen Mc Skyblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b070719305d2f4d849212db001b311552084f2c06a7a878b407f2f243767ca0"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
