name = "Kirisute Gomen Mc Skyblock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12c15e48682463ed49e8b8a0abe1c7a386098d89b0bb162ed55d23fcba6bc8fa"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
